import jsPDF from 'jspdf';
import { QuizResult } from '@/types';
import { format } from 'date-fns';

export function exportResultAsPdf(result: QuizResult) {
  const doc = new jsPDF();
  const { quiz, answers, score, percentage, timeTaken } = result;

  const primaryColor: [number, number, number] = [99, 102, 241];
  const grayColor: [number, number, number] = [107, 114, 128];

  // Header background
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 40, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('QuizAI Results', 14, 18);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Topic: ${quiz.config.topic}`, 14, 28);
  doc.text(`Difficulty: ${quiz.config.difficulty}`, 14, 35);

  // Score badge
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(155, 8, 42, 24, 4, 4, 'F');
  doc.setTextColor(...primaryColor);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(`${percentage}%`, 176, 22, { align: 'center' });

  // Stats row
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  const minutes = Math.floor(timeTaken / 60);
  const seconds = timeTaken % 60;

  doc.text(`Score: ${score}/${quiz.questions.length}`, 14, 52);
  doc.text(`Time: ${minutes}m ${seconds}s`, 80, 52);
  doc.text(`Date: ${format(new Date(result.completedAt), 'MMM d, yyyy')}`, 140, 52);

  // Divider
  doc.setDrawColor(220, 220, 220);
  doc.line(14, 57, 196, 57);

  // Questions
  let y = 66;

  quiz.questions.forEach((q, index) => {
    const answer = answers.find(a => a.questionId === q.id);
    const isCorrect = answer?.isCorrect ?? false;
    const selectedOption = answer?.selectedOption ?? -1;

    // Check page overflow
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    // Question number + result indicator
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(isCorrect ? 34 : 239, isCorrect ? 197 : 68, isCorrect ? 94 : 68);
    doc.text(isCorrect ? '✓' : '✗', 14, y);

    doc.setTextColor(30, 30, 30);
    const questionText = doc.splitTextToSize(`${index + 1}. ${q.question}`, 170);
    doc.text(questionText, 22, y);
    y += questionText.length * 5 + 2;

    // Selected answer
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);

    if (!isCorrect) {
      doc.setTextColor(239, 68, 68);
      const yourAnswer = selectedOption >= 0
        ? `Your answer: ${q.options[selectedOption]}`
        : 'Your answer: No answer (timed out)';
      doc.text(yourAnswer, 22, y);
      y += 5;

      doc.setTextColor(34, 197, 94);
      doc.text(`Correct: ${q.options[q.correctAnswer]}`, 22, y);
      y += 5;
    } else {
      doc.setTextColor(34, 197, 94);
      doc.text(`Correct: ${q.options[q.correctAnswer]}`, 22, y);
      y += 5;
    }

    // Explanation
    doc.setTextColor(...grayColor);
    const explanation = doc.splitTextToSize(`Explanation: ${q.explanation}`, 170);
    doc.text(explanation, 22, y);
    y += explanation.length * 4 + 6;

    // Small divider
    doc.setDrawColor(240, 240, 240);
    doc.line(14, y, 196, y);
    y += 5;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...grayColor);
    doc.text(`Generated by QuizAI · Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
  }

  doc.save(`QuizAI-${quiz.config.topic}-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
}